language: cpp

os: linux-ppc64le

sudo: required

services: docker

env:
    matrix:
    - RUN_ON_CONTAINER=fedora-rawhide

script:
    - docker build --pull -t ${RUN_ON_CONTAINER} -f lsvpd-ci/Dockerfile-${RUN_ON_CONTAINER} . &&
      docker run --volume $HOME/.ccache:/root/.ccache --volume `pwd`:/build --rm -t $RUN_ON_CONTAINER bash -c "./lsvpd-ci/build-${RUN_ON_CONTAINER}.sh";
